// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_sync_flutter_libs/objectbox_sync_flutter_libs.dart';

import 'model/cart.dart';
import 'model/category.dart';
import 'model/order.dart';
import 'model/products.dart';
import 'model/shipping.dart';
import 'model/user.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(2, 1755388395224074276),
      name: 'User',
      lastPropertyId: const IdUid(12, 4400796126597113461),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 5616583560322746149),
            name: 'userID',
            type: 9,
            flags: 2080,
            indexId: const IdUid(3, 6476017362766792001)),
        ModelProperty(
            id: const IdUid(2, 5666421421269216929),
            name: 'username',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 833669781507191727),
            name: 'email',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 8683178832145541436),
            name: 'password',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 3673235797466487800),
            name: 'fname',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 1327688660122397798),
            name: 'lname',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 9000778547250327128),
            name: 'image',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 1819689200144598835),
            name: 'uid',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(11, 3903809466668484519),
            name: 'role',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(12, 4400796126597113461),
            name: 'isFormFilled',
            type: 1,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(3, 7187338455050805458),
      name: 'Category',
      lastPropertyId: const IdUid(3, 474141437124168385),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 1699400926772092194),
            name: 'id',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(2, 5776092436057899631),
            name: 'categoryId',
            type: 9,
            flags: 2080,
            indexId: const IdUid(4, 564446221027492873)),
        ModelProperty(
            id: const IdUid(3, 474141437124168385),
            name: 'categoryName',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(5, 2409890910820290082),
      name: 'Product',
      lastPropertyId: const IdUid(7, 2941225911205876750),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 7738327543202863556),
            name: 'pid',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(2, 6969132237805402499),
            name: 'productId',
            type: 9,
            flags: 2080,
            indexId: const IdUid(7, 2486577352657672029)),
        ModelProperty(
            id: const IdUid(3, 4158691007582086077),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 2099848522967433553),
            name: 'price',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 1881896969669490870),
            name: 'image',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 8020643484745579237),
            name: 'description',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(6, 291713280849238794),
      name: 'Cart',
      lastPropertyId: const IdUid(4, 3419376355173592058),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 7967274557835704873),
            name: 'cId',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(2, 2563714116034711215),
            name: 'id',
            type: 9,
            flags: 2080,
            indexId: const IdUid(9, 6499321346681488044)),
        ModelProperty(
            id: const IdUid(3, 3580636338914637626),
            name: 'quantity',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 3419376355173592058),
            name: 'amount',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(7, 2380381452245525069),
      name: 'Address',
      lastPropertyId: const IdUid(5, 5316427282009509536),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 3663188147527702199),
            name: 'aId',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(2, 7994240555666506552),
            name: 'id',
            type: 9,
            flags: 2080,
            indexId: const IdUid(10, 7379108150831255693)),
        ModelProperty(
            id: const IdUid(3, 7112649403528944521),
            name: 'address',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 8874938428577883067),
            name: 'city',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 5316427282009509536),
            name: 'state',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(9, 8021527779818503360),
      name: 'Orders',
      lastPropertyId: const IdUid(5, 6468716421608972965),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 7234641504010962803),
            name: 'oId',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(2, 5084047470539008233),
            name: 'id',
            type: 9,
            flags: 2080,
            indexId: const IdUid(12, 8904002417790030518)),
        ModelProperty(
            id: const IdUid(3, 5609042260174173395),
            name: 'status',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 6468716421608972965),
            name: 'amount',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(9, 8021527779818503360),
      lastIndexId: const IdUid(12, 8904002417790030518),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [
        7858566292440967577,
        7955010377942542426,
        2302610575824903824
      ],
      retiredIndexUids: const [634105571500668049, 1643472555128223838],
      retiredPropertyUids: const [
        5916701203717393757,
        3475012209060386923,
        2706250535870486305,
        4844401363494620432,
        4723195987362991362,
        4695482223483438098,
        9005776117116850444,
        4421607327266596891,
        2372635048226451676,
        2756160670834519709,
        3912550364986977620,
        3525624406916190144,
        6510021609888275028,
        2941225911205876750,
        9132813870974850830,
        5999892614398620839,
        6117886093993083414,
        6943115804619216404
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    User: EntityDefinition<User>(
        model: _entities[0],
        toOneRelations: (User object) => [],
        toManyRelations: (User object) => {},
        getId: (User object) => object.uid,
        setId: (User object, int id) {
          object.uid = id;
        },
        objectToFB: (User object, fb.Builder fbb) {
          final userIDOffset =
              object.userID == null ? null : fbb.writeString(object.userID!);
          final usernameOffset = object.username == null
              ? null
              : fbb.writeString(object.username!);
          final emailOffset =
              object.email == null ? null : fbb.writeString(object.email!);
          final passwordOffset = object.password == null
              ? null
              : fbb.writeString(object.password!);
          final fnameOffset =
              object.fname == null ? null : fbb.writeString(object.fname!);
          final lnameOffset =
              object.lname == null ? null : fbb.writeString(object.lname!);
          final imageOffset =
              object.image == null ? null : fbb.writeString(object.image!);
          final roleOffset =
              object.role == null ? null : fbb.writeString(object.role!);
          fbb.startTable(13);
          fbb.addOffset(0, userIDOffset);
          fbb.addOffset(1, usernameOffset);
          fbb.addOffset(2, emailOffset);
          fbb.addOffset(3, passwordOffset);
          fbb.addOffset(6, fnameOffset);
          fbb.addOffset(7, lnameOffset);
          fbb.addOffset(8, imageOffset);
          fbb.addInt64(9, object.uid);
          fbb.addOffset(10, roleOffset);
          fbb.addBool(11, object.isFormFilled);
          fbb.finish(fbb.endTable());
          return object.uid;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = User(
              uid: const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
              userID: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 4),
              fname: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 16),
              lname: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 18),
              image: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 20),
              username: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6),
              password: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10),
              role: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 24),
              email:
                  const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 8),
              isFormFilled: const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 26));

          return object;
        }),
    Category: EntityDefinition<Category>(
        model: _entities[1],
        toOneRelations: (Category object) => [],
        toManyRelations: (Category object) => {},
        getId: (Category object) => object.id,
        setId: (Category object, int id) {
          object.id = id;
        },
        objectToFB: (Category object, fb.Builder fbb) {
          final categoryIdOffset = object.categoryId == null
              ? null
              : fbb.writeString(object.categoryId!);
          final categoryNameOffset = object.categoryName == null
              ? null
              : fbb.writeString(object.categoryName!);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, categoryIdOffset);
          fbb.addOffset(2, categoryNameOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Category(
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6),
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8),
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0));

          return object;
        }),
    Product: EntityDefinition<Product>(
        model: _entities[2],
        toOneRelations: (Product object) => [],
        toManyRelations: (Product object) => {},
        getId: (Product object) => object.pid,
        setId: (Product object, int id) {
          object.pid = id;
        },
        objectToFB: (Product object, fb.Builder fbb) {
          final productIdOffset = object.productId == null
              ? null
              : fbb.writeString(object.productId!);
          final nameOffset =
              object.name == null ? null : fbb.writeString(object.name!);
          final priceOffset =
              object.price == null ? null : fbb.writeString(object.price!);
          final imageOffset =
              object.image == null ? null : fbb.writeString(object.image!);
          final descriptionOffset = object.description == null
              ? null
              : fbb.writeString(object.description!);
          fbb.startTable(8);
          fbb.addInt64(0, object.pid);
          fbb.addOffset(1, productIdOffset);
          fbb.addOffset(2, nameOffset);
          fbb.addOffset(3, priceOffset);
          fbb.addOffset(4, imageOffset);
          fbb.addOffset(5, descriptionOffset);
          fbb.finish(fbb.endTable());
          return object.pid;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Product(
              productId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6),
              name: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8),
              price: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10),
              image: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12),
              description: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 14),
              pid: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0));

          return object;
        }),
    Cart: EntityDefinition<Cart>(
        model: _entities[3],
        toOneRelations: (Cart object) => [],
        toManyRelations: (Cart object) => {},
        getId: (Cart object) => object.cId,
        setId: (Cart object, int id) {
          object.cId = id;
        },
        objectToFB: (Cart object, fb.Builder fbb) {
          final idOffset =
              object.id == null ? null : fbb.writeString(object.id!);
          fbb.startTable(5);
          fbb.addInt64(0, object.cId);
          fbb.addOffset(1, idOffset);
          fbb.addInt64(2, object.quantity);
          fbb.addInt64(3, object.amount);
          fbb.finish(fbb.endTable());
          return object.cId;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Cart(
              id: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6),
              quantity: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 8),
              amount: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 10),
              cId: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0));

          return object;
        }),
    Address: EntityDefinition<Address>(
        model: _entities[4],
        toOneRelations: (Address object) => [],
        toManyRelations: (Address object) => {},
        getId: (Address object) => object.aId,
        setId: (Address object, int id) {
          object.aId = id;
        },
        objectToFB: (Address object, fb.Builder fbb) {
          final idOffset =
              object.id == null ? null : fbb.writeString(object.id!);
          final addressOffset =
              object.address == null ? null : fbb.writeString(object.address!);
          final cityOffset =
              object.city == null ? null : fbb.writeString(object.city!);
          final stateOffset =
              object.state == null ? null : fbb.writeString(object.state!);
          fbb.startTable(6);
          fbb.addInt64(0, object.aId);
          fbb.addOffset(1, idOffset);
          fbb.addOffset(2, addressOffset);
          fbb.addOffset(3, cityOffset);
          fbb.addOffset(4, stateOffset);
          fbb.finish(fbb.endTable());
          return object.aId;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Address(
              id: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6),
              address: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8),
              city: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10),
              state: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12),
              aId: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0));

          return object;
        }),
    Orders: EntityDefinition<Orders>(
        model: _entities[5],
        toOneRelations: (Orders object) => [],
        toManyRelations: (Orders object) => {},
        getId: (Orders object) => object.oId,
        setId: (Orders object, int id) {
          object.oId = id;
        },
        objectToFB: (Orders object, fb.Builder fbb) {
          final idOffset =
              object.id == null ? null : fbb.writeString(object.id!);
          final statusOffset =
              object.status == null ? null : fbb.writeString(object.status!);
          fbb.startTable(6);
          fbb.addInt64(0, object.oId);
          fbb.addOffset(1, idOffset);
          fbb.addOffset(2, statusOffset);
          fbb.addInt64(4, object.amount);
          fbb.finish(fbb.endTable());
          return object.oId;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Orders(
              id: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6),
              amount: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 12),
              status: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8),
              oId: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [User] entity fields to define ObjectBox queries.
class User_ {
  /// see [User.userID]
  static final userID = QueryStringProperty<User>(_entities[0].properties[0]);

  /// see [User.username]
  static final username = QueryStringProperty<User>(_entities[0].properties[1]);

  /// see [User.email]
  static final email = QueryStringProperty<User>(_entities[0].properties[2]);

  /// see [User.password]
  static final password = QueryStringProperty<User>(_entities[0].properties[3]);

  /// see [User.fname]
  static final fname = QueryStringProperty<User>(_entities[0].properties[4]);

  /// see [User.lname]
  static final lname = QueryStringProperty<User>(_entities[0].properties[5]);

  /// see [User.image]
  static final image = QueryStringProperty<User>(_entities[0].properties[6]);

  /// see [User.uid]
  static final uid = QueryIntegerProperty<User>(_entities[0].properties[7]);

  /// see [User.role]
  static final role = QueryStringProperty<User>(_entities[0].properties[8]);

  /// see [User.isFormFilled]
  static final isFormFilled =
      QueryBooleanProperty<User>(_entities[0].properties[9]);
}

/// [Category] entity fields to define ObjectBox queries.
class Category_ {
  /// see [Category.id]
  static final id = QueryIntegerProperty<Category>(_entities[1].properties[0]);

  /// see [Category.categoryId]
  static final categoryId =
      QueryStringProperty<Category>(_entities[1].properties[1]);

  /// see [Category.categoryName]
  static final categoryName =
      QueryStringProperty<Category>(_entities[1].properties[2]);
}

/// [Product] entity fields to define ObjectBox queries.
class Product_ {
  /// see [Product.pid]
  static final pid = QueryIntegerProperty<Product>(_entities[2].properties[0]);

  /// see [Product.productId]
  static final productId =
      QueryStringProperty<Product>(_entities[2].properties[1]);

  /// see [Product.name]
  static final name = QueryStringProperty<Product>(_entities[2].properties[2]);

  /// see [Product.price]
  static final price = QueryStringProperty<Product>(_entities[2].properties[3]);

  /// see [Product.image]
  static final image = QueryStringProperty<Product>(_entities[2].properties[4]);

  /// see [Product.description]
  static final description =
      QueryStringProperty<Product>(_entities[2].properties[5]);
}

/// [Cart] entity fields to define ObjectBox queries.
class Cart_ {
  /// see [Cart.cId]
  static final cId = QueryIntegerProperty<Cart>(_entities[3].properties[0]);

  /// see [Cart.id]
  static final id = QueryStringProperty<Cart>(_entities[3].properties[1]);

  /// see [Cart.quantity]
  static final quantity =
      QueryIntegerProperty<Cart>(_entities[3].properties[2]);

  /// see [Cart.amount]
  static final amount = QueryIntegerProperty<Cart>(_entities[3].properties[3]);
}

/// [Address] entity fields to define ObjectBox queries.
class Address_ {
  /// see [Address.aId]
  static final aId = QueryIntegerProperty<Address>(_entities[4].properties[0]);

  /// see [Address.id]
  static final id = QueryStringProperty<Address>(_entities[4].properties[1]);

  /// see [Address.address]
  static final address =
      QueryStringProperty<Address>(_entities[4].properties[2]);

  /// see [Address.city]
  static final city = QueryStringProperty<Address>(_entities[4].properties[3]);

  /// see [Address.state]
  static final state = QueryStringProperty<Address>(_entities[4].properties[4]);
}

/// [Orders] entity fields to define ObjectBox queries.
class Orders_ {
  /// see [Orders.oId]
  static final oId = QueryIntegerProperty<Orders>(_entities[5].properties[0]);

  /// see [Orders.id]
  static final id = QueryStringProperty<Orders>(_entities[5].properties[1]);

  /// see [Orders.status]
  static final status = QueryStringProperty<Orders>(_entities[5].properties[2]);

  /// see [Orders.amount]
  static final amount =
      QueryIntegerProperty<Orders>(_entities[5].properties[3]);
}
